import 'dart:io';
import 'package:path/path.dart' as p;

enum StoreMode { gms, hms, hybrid }

class AppCodeConfigurator {
  // New target directory: lib/generated/store_service
  final String _targetDir = 'lib/generated/store_service';
  final String _targetStoreService =
      'lib/generated/store_service/store_service.dart';
  final String _targetServicesDir = 'lib/generated/store_service/services';

  Future<void> apply(StoreMode mode) async {
    print(
      '🔧 Generating StoreService configuration for ${mode.name.toUpperCase()}...',
    );

    final packageName = await _getPackageName();
    final templatesDir = await _findTemplatesDir();

    // Ensure target directories exist
    await Directory(_targetDir).create(recursive: true);
    await Directory(_targetServicesDir).create(recursive: true);

    // 1. Copy Service Templates (Firebase/HMS)
    if (mode == StoreMode.gms || mode == StoreMode.hybrid) {
      await _copyTemplate(
        templatesDir,
        'services/firebase_service.dart',
        '$_targetServicesDir/firebase_service.dart',
        packageName,
      );
    }

    if (mode == StoreMode.hms || mode == StoreMode.hybrid) {
      await _copyTemplate(
        templatesDir,
        'services/hms_service.dart',
        '$_targetServicesDir/hms_service.dart',
        packageName,
      );
    }

    // 2. Copy Interfaces
    await _copyTemplate(
      templatesDir,
      'store_interfaces.dart',
      p.join(_targetDir, 'store_interfaces.dart'),
      packageName,
    );

    // 3. Generate StoreService
    String templateName;
    switch (mode) {
      case StoreMode.gms:
        templateName = 'store_service_gms.dart';
        break;
      case StoreMode.hms:
        templateName = 'store_service_hms.dart';
        break;
      case StoreMode.hybrid:
        templateName = 'store_service_hybrid.dart';
        break;
    }

    await _copyTemplate(
      templatesDir,
      templateName,
      _targetStoreService,
      packageName,
    );
  }

  Future<void> _copyTemplate(
    Directory templatesDir,
    String templateParam,
    String targetPath,
    String packageName,
  ) async {
    final templateFile = File('${templatesDir.path}/$templateParam');
    if (!await templateFile.exists()) {
      throw Exception('Template not found: ${templateFile.path}');
    }

    var content = await templateFile.readAsString();

    // Add Warning Header
    const header = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// This code is generated by store_services_cli.
// Any changes to this file will be overwritten.

''';

    final targetFile = File(targetPath);
    await targetFile.create(recursive: true);
    await targetFile.writeAsString(header + content);
    print('  ✅ Generated $targetPath');
  }

  Future<Directory> _findTemplatesDir() async {
    // 1. Check current directory (dev mode)
    if (await Directory('lib/templates').exists()) {
      return Directory('lib/templates');
    }
    // 2. Check parent (if running from test/test_app)
    if (await Directory('../../lib/templates').exists()) {
      return Directory('../../lib/templates');
    }
    // 3. Check script location
    final scriptDir = File(Platform.script.toFilePath()).parent;
    // script is in bin/, templates in lib/templates which is ../lib/templates from bin
    final fromScript = Directory('${scriptDir.parent.path}/lib/templates');
    if (await fromScript.exists()) {
      return fromScript;
    }

    throw Exception(
      'Could not locate lib/templates directory. Checked: lib/templates, ../../lib/templates, ${fromScript.path}',
    );
  }

  Future<String> _getPackageName() async {
    final pubspec = File('pubspec.yaml');
    if (!await pubspec.exists()) {
      return 'app'; // fallback
    }
    final lines = await pubspec.readAsLines();
    for (var line in lines) {
      if (line.startsWith('name:')) {
        return line.split(':')[1].trim();
      }
    }
    return 'app';
  }

  Future<void> remove() async {
    print('🧹 Cleaning generated store codes...');
    final dir = Directory(_targetDir);
    if (await dir.exists()) {
      await dir.delete(recursive: true);
      print('  ✅ Removed $_targetDir');
    }

    // Also try to clean old location just in case
    final oldFile = File('lib/store_service.dart');
    if (await oldFile.exists()) {
      await oldFile.delete();
      print('  ✅ Removed legacy lib/store_service.dart');
    }
    final oldDir = Directory('lib/services');
    if (await oldDir.exists()) {
      // Safety: Only delete known files?
      final f1 = File('lib/services/firebase_service.dart');
      if (await f1.exists()) await f1.delete();
      final f2 = File('lib/services/hms_service.dart');
      if (await f2.exists()) await f2.delete();

      // If empty, delete dir
      if (await oldDir.list().isEmpty) {
        await oldDir.delete();
        print('  ✅ Removed legacy lib/services directory');
      }
    }
  }
}
